…

diff --git a/etc/ci/update-wpt-checkout b/etc/ci/update-wpt-checkout
--- a/etc/ci/update-wpt-checkout
+++ b/etc/ci/update-wpt-checkout
@@ -66,17 +66,18 @@ function cleanup() {
 
 # Build Servo and run the full WPT testsuite, saving the results to a log file.
 function unsafe_run_tests() {
-    # Run the full testsuite and record the new test results.
-    ./mach test-wpt --release --processes 12 --log-raw "${1}" \
-           --always-succeed || return 1
+    return
+#    # Run the full testsuite and record the new test results.
+#    ./mach test-wpt --release --processes 12 --log-raw "${1}" \
+#           --always-succeed || return 1
 
-    # Run the bluetooth testsuite, which uses the webdriver test harness.
-    ./mach test-wpt --release --product=servodriver --headless \
-           --log-raw "${2}" /bluetooth --always-succeed || return 2
+#    # Run the bluetooth testsuite, which uses the webdriver test harness.
+#    ./mach test-wpt --release --product=servodriver --headless \
+#           --log-raw "${2}" /bluetooth --always-succeed || return 2
 
-    # Run the wdspec testsuite
-    ./mach test-wpt --release --timeout-multiplier=4 --log-raw "${3}" /webdriver \
-           --always-succeed || return 3
+#    # Run the wdspec testsuite
+#    ./mach test-wpt --release --timeout-multiplier=4 --log-raw "${3}" /webdriver \
+#           --always-succeed || return 3
 }
 
 # Using an existing log file, update the expected test results and amend the
@@ -99,48 +100,48 @@ function unsafe_open_pull_request() {
     # is unnecessary.
     git checkout "${BRANCH_NAME}" || return 0
 
-    if [[ -z "${WPT_SYNC_TOKEN+set}" && "${TASKCLUSTER_PROXY_URL+set}" == "set" ]]; then
-        SECRET_RESPONSE=$(curl ${TASKCLUSTER_PROXY_URL}/api/secrets/v1/secret/project/servo/wpt-sync)
-        WPT_SYNC_TOKEN=`echo "${SECRET_RESPONSE}" | jq --raw-output '.secret.token'`
-    fi
+#    if [[ -z "${WPT_SYNC_TOKEN+set}" && "${TASKCLUSTER_PROXY_URL+set}" == "set" ]]; then
+#        SECRET_RESPONSE=$(curl ${TASKCLUSTER_PROXY_URL}/api/secrets/v1/secret/project/servo/wpt-sync)
+#        WPT_SYNC_TOKEN=`echo "${SECRET_RESPONSE}" | jq --raw-output '.secret.token'`
+#    fi
 
-    if [[ -z "${WPT_SYNC_TOKEN+set}" ]]; then
-        echo "Github auth token missing from WPT_SYNC_TOKEN."
-        return 1
-    fi
+#    if [[ -z "${WPT_SYNC_TOKEN+set}" ]]; then
+#        echo "Github auth token missing from WPT_SYNC_TOKEN."
+#        return 1
+#    fi
 
-    # Push the changes to a remote branch owned by the bot.
-    AUTH="${WPT_SYNC_USER}:${WPT_SYNC_TOKEN}"
-    UPSTREAM="https://${AUTH}@github.com/${WPT_SYNC_USER}/servo.git"
-    git remote add "${REMOTE_NAME}" "${UPSTREAM}" || return 2
-    git push -f "${REMOTE_NAME}" "${BRANCH_NAME}:${REMOTE_BRANCH_NAME}" &>/dev/null || return 3
+#    # Push the changes to a remote branch owned by the bot.
+#    AUTH="${WPT_SYNC_USER}:${WPT_SYNC_TOKEN}"
+#    UPSTREAM="https://${AUTH}@github.com/${WPT_SYNC_USER}/servo.git"
+#    git remote add "${REMOTE_NAME}" "${UPSTREAM}" || return 2
+#    git push -f "${REMOTE_NAME}" "${BRANCH_NAME}:${REMOTE_BRANCH_NAME}" &>/dev/null || return 3
 
-    # Prepare the pull request metadata.
-    BODY="Automated downstream sync of changes from upstream as of "
-    BODY+="${CURRENT_DATE}.\n"
-    BODY+="[no-wpt-sync]\n"
-    BODY+="r? @servo-wpt-sync\n"
-    cat <<EOF >prdata.json || return 4
-{
-  "title": "Sync WPT with upstream (${CURRENT_DATE})",
-  "head": "${WPT_SYNC_USER}:${REMOTE_BRANCH_NAME}",
-  "base": "master",
-  "body": "${BODY}",
-  "maintainer_can_modify": true
-}
-EOF
+#    # Prepare the pull request metadata.
+#    BODY="Automated downstream sync of changes from upstream as of "
+#    BODY+="${CURRENT_DATE}.\n"
+#    BODY+="[no-wpt-sync]\n"
+#    BODY+="r? @servo-wpt-sync\n"
+#    cat <<EOF >prdata.json || return 4
+#{
+#  "title": "Sync WPT with upstream (${CURRENT_DATE})",
+#  "head": "${WPT_SYNC_USER}:${REMOTE_BRANCH_NAME}",
+#  "base": "master",
+#  "body": "${BODY}",
+#  "maintainer_can_modify": true
+#}
+#EOF
 
-    # Open a pull request using the new branch.
-    OPEN_PR_RESPONSE=$(curl -H "Authorization: token ${WPT_SYNC_TOKEN}" \
-                            -H "Content-Type: application/json" \
-                            --data @prdata.json \
-                            https://api.github.com/repos/servo/servo/pulls) || return 5
+#    # Open a pull request using the new branch.
+#    OPEN_PR_RESPONSE=$(curl -H "Authorization: token ${WPT_SYNC_TOKEN}" \
+#                            -H "Content-Type: application/json" \
+#                            --data @prdata.json \
+#                            https://api.github.com/repos/servo/servo/pulls) || return 5
 
-    echo "${OPEN_PR_RESPONSE}" | \
-        jq '.review_comments_url' | \
-        sed 's/pulls/issues/' | \
-        xargs curl -H "Authorization: token ${WPT_SYNC_TOKEN}" \
-                   --data "{\"body\":\"@bors-servo r+\"}" || return 6
+#    echo "${OPEN_PR_RESPONSE}" | \
+#        jq '.review_comments_url' | \
+#        sed 's/pulls/issues/' | \
+#        xargs curl -H "Authorization: token ${WPT_SYNC_TOKEN}" \
+#                   --data "{\"body\":\"@bors-servo r+\"}" || return 6
 }
 
 function pull_from_upstream() {
